(#39) Set up integration tests. - Add bestbets-loader as a submodule. - Load bestbets content as of July 31, 2020. - Port old integration tests into new system.

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -144,10 +144,13 @@ jobs:
               ## Create test output and API logging location
               mkdir -p integration-tests/target
 
-#              ## Load the elasticsearch data
-#              ./integration-tests/bin/load-integration-data.sh
+              ## Load the elasticsearch data
+              ./integration-tests/bin/load-integration-data.sh
+
       - name: Start API
         env:
+          CGBestBetsIndex__PreviewAliasName: bestbets_v1
+          CGBestBetsIndex__LiveAliasName: bestbets_v1
           Elasticsearch__Servers: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
           ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: true
           API_URL: http://localhost:5000
@@ -178,30 +181,30 @@ jobs:
               done
 
               echo "API is up"
-#      - name: Run Integration Test
-#        ## Normally bash runs with -e which exits the shell upon hitting
-#        ## an error which breaks our capturing of those errors.
-#        shell: bash --noprofile --norc -o pipefail {0}
-#        run: |
-#              ## Run Karate
-#              cd integration-tests && ./bin/karate ./features
-#
-#              ## Store the exit code off so we can pass this step and
-#              ## capture the test output in the next step, but still
-#              ## fail the entire job
-#              echo ::set-env name=TEST_EXIT_CODE::$?
-#              exit 0
-#      - name: Upload Integration test results
-#        uses: actions/upload-artifact@v1
-#        with:
-#          name: integration-test-results
-#          path: integration-tests/target
-#      - name: Fail build on bad tests
-#        run: |
-#              ## Check if we had errors on the test step, and if so, fail the job
-#              if [ $TEST_EXIT_CODE -ne 0 ]; then
-#                echo "Tests Failed -- See Run Integration Test step or integration-test-results artifact for more information"
-#                exit $TEST_EXIT_CODE
-#              else
-#                echo "Tests passed"
-#              fi
+      - name: Run Integration Test
+        ## Normally bash runs with -e which exits the shell upon hitting
+        ## an error which breaks our capturing of those errors.
+        shell: bash --noprofile --norc -o pipefail {0}
+        run: |
+              ## Run Karate
+              cd integration-tests && ./bin/karate ./features
+
+              ## Store the exit code off so we can pass this step and
+              ## capture the test output in the next step, but still
+              ## fail the entire job
+              echo ::set-env name=TEST_EXIT_CODE::$?
+              exit 0
+      - name: Upload Integration test results
+        uses: actions/upload-artifact@v1
+        with:
+          name: integration-test-results
+          path: integration-tests/target
+      - name: Fail build on bad tests
+        run: |
+              ## Check if we had errors on the test step, and if so, fail the job
+              if [ $TEST_EXIT_CODE -ne 0 ]; then
+                echo "Tests Failed -- See Run Integration Test step or integration-test-results artifact for more information"
+                exit $TEST_EXIT_CODE
+              else
+                echo "Tests passed"
+              fi
